    import json
import os
from typing import Any, Dict, Optional

import requests
from google.auth import default
from google.auth.transport.requests import Request


class FHIRClient:
    """
    Handles read/write operations against the GCP FHIR store.
    """

    def __init__(
        self,
        project_id: Optional[str] = None,
        location: str = "us-central1",
        dataset_id: str = "adpo-dataset",
        fhir_store: str = "adpo-fhir-store",
    ) -> None:
        self.project_id = project_id or os.getenv("PROJECT_ID", "")
        self.location = location
        self.dataset_id = dataset_id
        self.fhir_store = fhir_store

        if not self.project_id:
            raise ValueError("PROJECT_ID is missing. Set it as an environment variable.")

        self.base_url = (
            f"https://healthcare.googleapis.com/v1/projects/{self.project_id}/"
            f"locations/{self.location}/datasets/{self.dataset_id}/"
            f"fhirStores/{self.fhir_store}/fhir"
        )

    def _auth_headers(self) -> Dict[str, str]:
        creds, _ = default(scopes=["https://www.googleapis.com/auth/cloud-healthcare"])
        creds.refresh(Request())
        return {
            "Authorization": f"Bearer {creds.token}",
            "Content-Type": "application/fhir+json",
        }

    def get_patient(self, patient_id: str) -> Dict[str, Any]:
        response = requests.get(
            f"{self.base_url}/Patient/{patient_id}",
            headers=self._auth_headers(),
            timeout=30,
        )
        response.raise_for_status()
        return response.json()

    def get_latest_observation(self, patient_id: str, loinc_code: str) -> Optional[Dict[str, Any]]:
        params = {
            "patient": patient_id,
            "code": loinc_code,
            "_sort": "-date",
            "_count": "1",
        }

        response = requests.get(
            f"{self.base_url}/Observation",
            params=params,
            headers=self._auth_headers(),
            timeout=30,
        )
        response.raise_for_status()

        bundle = response.json()
        if bundle.get("total", 0) == 0:
            return None

        return bundle["entry"][0]["resource"]

    def create_service_request(
        self,
        patient_id: str,
        order_code: str,
        order_name: str,
        source_obs_id: str,
        priority: str = "routine",
    ) -> Dict[str, Any]:
        service_request = {
            "resourceType": "ServiceRequest",
            "status": "active",
            "intent": "order",
            "priority": priority.lower(),
            "code": {
                "coding": [
                    {
                        "system": "http://loinc.org",
                        "code": order_code,
                        "display": order_name,
                    }
                ]
            },
            "subject": {"reference": f"Patient/{patient_id}"},
            "basedOn": [{"reference": f"Observation/{source_obs_id}"}],
            "note": [{"text": "Auto-generated by ADPO AI Agent"}],
        }

        response = requests.post(
            f"{self.base_url}/ServiceRequest",
            data=json.dumps(service_request),
            headers=self._auth_headers(),
            timeout=30,
        )
        response.raise_for_status()
        return response.json()