import json
import os
from typing import Optional, Dict, Any

import requests
from google.auth import default
from google.auth.transport.requests import Request


class FHIRClient:
    """
    Handles FHIR interactions with Google Cloud Healthcare API
    """

    def __init__(
        self,
        project_id: Optional[str] = None,
        location: str = "us-central1",
        dataset_id: str = "adpo-dataset",
        fhir_store: str = "adpo-fhir-store",
    ):
        self.project_id = (
            project_id
            or os.getenv("PROJECT_ID")
            or os.getenv("GOOGLE_CLOUD_PROJECT")
        )

        if not self.project_id:
            raise ValueError("PROJECT_ID or GOOGLE_CLOUD_PROJECT not set")

        self.location = location
        self.dataset_id = dataset_id
        self.fhir_store = fhir_store

        self.base_url = (
            f"https://healthcare.googleapis.com/v1/projects/{self.project_id}/"
            f"locations/{self.location}/datasets/{self.dataset_id}/"
            f"fhirStores/{self.fhir_store}/fhir"
        )

    def _auth_headers(self) -> Dict[str, str]:
        creds, _ = default(
            scopes=["https://www.googleapis.com/auth/cloud-healthcare"]
        )
        creds.refresh(Request())

        return {
            "Authorization": f"Bearer {creds.token}",
            "Content-Type": "application/fhir+json",
        }

    def create_service_request(
        self,
        patient_id: str,
        order_code: str,
        order_name: str,
        source_obs_id: str,
        priority: str = "routine",
    ) -> Dict[str, Any]:
        """
        Creates a ServiceRequest in FHIR store
        """

        payload = {
            "resourceType": "ServiceRequest",
            "status": "active",
            "intent": "order",
            "priority": priority.lower(),
            "subject": {
                "reference": f"Patient/{patient_id}"
            },
            "code": {
                "coding": [
                    {
                        "system": "http://loinc.org",
                        "code": order_code,
                        "display": order_name
                    }
                ],
                "text": order_name
            },
            "reasonReference": [
                {
                    "reference": f"Observation/{source_obs_id}"
                }
            ],
            "note": [
                {
                    "text": f"Auto-generated by ADPO AI Agent from Observation/{source_obs_id}"
                }
            ]
        }

        response = requests.post(
            f"{self.base_url}/ServiceRequest",
            headers=self._auth_headers(),
            data=json.dumps(payload),
            timeout=30,
        )

        # Debug logs if error occurs
        if not response.ok:
            print("[FHIR ERROR STATUS]", response.status_code)
            print("[FHIR ERROR BODY]", response.text)

        response.raise_for_status()
        return response.json()